[project]
name = "python-opentelemetry-access"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Tilo Wiklund", email = "tilo.wiklund@sensmetry.com" } 
]
requires-python = ">=3.11"
dependencies = [
    "opentelemetry-betterproto",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = [
    "pytest>=8.3.3",
]

[tool.uv.sources]
opentelemetry-betterproto = { git = "https://github.com/EOEPCA/opentelemetry-betterproto.git" }

[tool.pytest.ini_options]
testpaths = ["tests"]
