[project]
name = "python-opentelemetry-access"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Tilo Wiklund", email = "tilo.wiklund@sensmetry.com" } 
]
requires-python = ">=3.11"
dependencies = [
    "click>=8.1.7",
    "fastapi>=0.115.4",
    "opensearch-py[async]>=2.7.1",
    "opentelemetry-betterproto",
    "pandas>=2.2.3",
    "uvicorn>=0.32.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = [
    "pandas-stubs>=2.2.3.241009",
    "pytest>=8.3.3",
]

[tool.uv.sources]
opentelemetry-betterproto = { git = "https://github.com/EOEPCA/opentelemetry-betterproto.git" }

[tool.pytest.ini_options]
testpaths = ["tests"]
